return {
	"cursor-midnight",
	name = "cursor-midnight",
	dev = true,
	enabled = false,
	lazy = false,
	priority = 1000,
	config = function()
		local colors = {
			-- Koda-inspired dark background
			bg = "#101010",
			bg_alt = "#161616",
			bg_highlight = "#1e1e1e",
			-- Muted foreground like koda
			fg = "#b0b0b0",
			fg_dim = "#50585d",
			emphasis = "#ffffff",
			-- Accent colors (muted versions)
			blue = "#8ebeec",
			cyan = "#7ec8c8",
			green = "#86cd82",
			magenta = "#a08dc0",
			orange = "#d9ba73",
			pink = "#c9a0b8",
			red = "#ff7676",
			yellow = "#d9ba73",
			purple = "#a08dc0",
			-- Koda-style muted keywords
			keyword = "#777777",
			comment = "#50585d",
			selection = "#0058d0",
			line_nr = "#3a3a3a",
			cursor_line = "#1a1a1a",
			property = "#9090a0",
			paren = "#4d4d4d",
		}

		local highlights = {
			-- Editor (Koda-inspired dark)
			Normal = { fg = colors.fg, bg = colors.bg },
			NormalFloat = { fg = colors.fg, bg = colors.bg_alt },
			FloatBorder = { fg = colors.paren, bg = colors.bg_alt },
			Cursor = { fg = colors.bg, bg = colors.emphasis },
			CursorLine = { bg = colors.cursor_line },
			CursorLineNr = { fg = colors.emphasis, bold = true },
			LineNr = { fg = colors.line_nr },
			SignColumn = { bg = colors.bg },
			Visual = { bg = colors.selection },
			Search = { fg = colors.bg, bg = colors.orange },
			IncSearch = { fg = colors.bg, bg = colors.emphasis },
			Pmenu = { fg = colors.fg, bg = colors.bg_alt },
			PmenuSel = { fg = colors.emphasis, bg = colors.selection },
			PmenuThumb = { bg = colors.paren },
			StatusLine = { fg = colors.fg, bg = colors.bg_alt },
			StatusLineNC = { fg = colors.fg_dim, bg = colors.bg_alt },
			WinSeparator = { fg = colors.bg_highlight },
			VertSplit = { fg = colors.bg_highlight },
			TabLine = { fg = colors.fg_dim, bg = colors.bg_alt },
			TabLineFill = { bg = colors.bg },
			TabLineSel = { fg = colors.emphasis, bg = colors.bg },
			Title = { fg = colors.emphasis, bold = true },
			Directory = { fg = colors.emphasis },
			MatchParen = { fg = colors.orange, bold = true },
			NonText = { fg = colors.bg_highlight },
			Whitespace = { fg = colors.bg_highlight },
			SpecialKey = { fg = colors.bg_highlight },
			EndOfBuffer = { fg = colors.bg },
			Folded = { fg = colors.comment, bg = colors.bg_alt },
			FoldColumn = { fg = colors.comment, bg = colors.bg },
			ColorColumn = { bg = colors.bg_alt },
			ErrorMsg = { fg = colors.red },
			WarningMsg = { fg = colors.orange },
			Question = { fg = colors.emphasis },
			MoreMsg = { fg = colors.emphasis },
			ModeMsg = { fg = colors.fg },

			-- Syntax (Koda-inspired: white emphasis, gray keywords)
			Comment = { fg = colors.comment, italic = true },
			Constant = { fg = colors.orange },
			String = { fg = colors.emphasis },
			Character = { fg = colors.emphasis },
			Number = { fg = colors.orange },
			Boolean = { fg = colors.orange },
			Float = { fg = colors.orange },
			Identifier = { fg = colors.fg },
			Function = { fg = colors.emphasis },
			Statement = { fg = colors.keyword },
			Keyword = { fg = colors.keyword },
			Conditional = { fg = colors.keyword },
			Repeat = { fg = colors.keyword },
			Label = { fg = colors.keyword },
			Operator = { fg = colors.keyword },
			Exception = { fg = colors.keyword },
			PreProc = { fg = colors.fg },
			Include = { fg = colors.keyword },
			Define = { fg = colors.keyword },
			Macro = { fg = colors.orange },
			PreCondit = { fg = colors.keyword },
			Type = { fg = colors.keyword },
			StorageClass = { fg = colors.keyword },
			Structure = { fg = colors.keyword },
			Typedef = { fg = colors.keyword },
			Special = { fg = colors.fg },
			SpecialChar = { fg = colors.cyan },
			Tag = { fg = colors.fg },
			Delimiter = { fg = colors.emphasis },
			SpecialComment = { fg = colors.comment },
			Debug = { fg = colors.orange },
			Underlined = { underline = true },
			Ignore = { fg = colors.bg_highlight },
			Error = { fg = colors.red },
			Todo = { fg = colors.bg, bg = colors.orange, bold = true },

			-- Treesitter (Koda-inspired: white emphasis, gray keywords, muted colors)
			["@variable"] = { fg = colors.fg },
			["@variable.builtin"] = { fg = colors.fg },
			["@variable.parameter"] = { fg = colors.fg, italic = true },
			["@variable.member"] = { fg = colors.property },
			["@constant"] = { fg = colors.orange },
			["@constant.builtin"] = { fg = colors.orange },
			["@constant.macro"] = { fg = colors.orange },
			["@module"] = { fg = colors.fg },
			["@label"] = { fg = colors.keyword },
			["@string"] = { fg = colors.emphasis },
			["@string.escape"] = { fg = colors.cyan },
			["@string.regexp"] = { fg = colors.cyan },
			["@character"] = { fg = colors.emphasis },
			["@number"] = { fg = colors.orange },
			["@number.float"] = { fg = colors.orange },
			["@boolean"] = { fg = colors.orange },
			["@type"] = { fg = colors.keyword },
			["@type.builtin"] = { fg = colors.keyword },
			["@type.definition"] = { fg = colors.keyword },
			["@attribute"] = { fg = colors.keyword },
			["@property"] = { fg = colors.property },
			["@function"] = { fg = colors.emphasis },
			["@function.call"] = { fg = colors.emphasis },
			["@function.builtin"] = { fg = colors.emphasis },
			["@function.macro"] = { fg = colors.emphasis },
			["@function.method"] = { fg = colors.emphasis },
			["@function.method.call"] = { fg = colors.emphasis },
			["@constructor"] = { fg = colors.emphasis },
			["@operator"] = { fg = colors.keyword },
			["@keyword"] = { fg = colors.keyword },
			["@keyword.coroutine"] = { fg = colors.keyword },
			["@keyword.function"] = { fg = colors.keyword },
			["@keyword.operator"] = { fg = colors.keyword },
			["@keyword.import"] = { fg = colors.keyword },
			["@keyword.storage"] = { fg = colors.keyword },
			["@keyword.repeat"] = { fg = colors.keyword },
			["@keyword.return"] = { fg = colors.keyword },
			["@keyword.exception"] = { fg = colors.keyword },
			["@keyword.conditional"] = { fg = colors.keyword },
			["@punctuation.delimiter"] = { fg = colors.paren },
			["@punctuation.bracket"] = { fg = colors.paren },
			["@punctuation.special"] = { fg = colors.emphasis },
			["@comment"] = { fg = colors.comment, italic = true },
			["@comment.todo"] = { fg = colors.bg, bg = colors.orange, bold = true },
			["@comment.note"] = { fg = colors.bg, bg = colors.blue, bold = true },
			["@comment.warning"] = { fg = colors.bg, bg = colors.orange, bold = true },
			["@comment.error"] = { fg = colors.bg, bg = colors.red, bold = true },
			["@markup.heading"] = { fg = colors.emphasis, bold = true },
			["@markup.strong"] = { bold = true },
			["@markup.italic"] = { italic = true },
			["@markup.link"] = { fg = colors.blue, underline = true },
			["@markup.link.url"] = { fg = colors.blue, underline = true },
			["@markup.raw"] = { fg = colors.emphasis },
			["@markup.list"] = { fg = colors.keyword },
			["@tag"] = { fg = colors.emphasis },
			["@tag.attribute"] = { fg = colors.property },
			["@tag.delimiter"] = { fg = colors.paren },

			-- LSP Semantic Tokens (Koda-inspired)
			["@lsp.type.class"] = { fg = colors.keyword },
			["@lsp.type.decorator"] = { fg = colors.keyword },
			["@lsp.type.enum"] = { fg = colors.keyword },
			["@lsp.type.enumMember"] = { fg = colors.orange },
			["@lsp.type.function"] = { fg = colors.emphasis },
			["@lsp.type.interface"] = { fg = colors.keyword },
			["@lsp.type.macro"] = { fg = colors.orange },
			["@lsp.type.method"] = { fg = colors.emphasis },
			["@lsp.type.namespace"] = { fg = colors.fg },
			["@lsp.type.parameter"] = { fg = colors.fg, italic = true },
			["@lsp.type.property"] = { fg = colors.property },
			["@lsp.type.struct"] = { fg = colors.keyword },
			["@lsp.type.type"] = { fg = colors.keyword },
			["@lsp.type.typeParameter"] = { fg = colors.keyword },
			["@lsp.type.variable"] = { fg = colors.fg },

			-- Diagnostics
			DiagnosticError = { fg = colors.red },
			DiagnosticWarn = { fg = colors.yellow },
			DiagnosticInfo = { fg = colors.blue },
			DiagnosticHint = { fg = colors.cyan },
			DiagnosticUnderlineError = { undercurl = true, sp = colors.red },
			DiagnosticUnderlineWarn = { undercurl = true, sp = colors.yellow },
			DiagnosticUnderlineInfo = { undercurl = true, sp = colors.blue },
			DiagnosticUnderlineHint = { undercurl = true, sp = colors.cyan },
			DiagnosticVirtualTextError = { fg = colors.red, bg = colors.bg_alt },
			DiagnosticVirtualTextWarn = { fg = colors.yellow, bg = colors.bg_alt },
			DiagnosticVirtualTextInfo = { fg = colors.blue, bg = colors.bg_alt },
			DiagnosticVirtualTextHint = { fg = colors.cyan, bg = colors.bg_alt },
			DiagnosticFloatingError = { fg = colors.red },
			DiagnosticFloatingWarn = { fg = colors.yellow },
			DiagnosticFloatingInfo = { fg = colors.blue },
			DiagnosticFloatingHint = { fg = colors.cyan },
			DiagnosticSignError = { fg = colors.red },
			DiagnosticSignWarn = { fg = colors.yellow },
			DiagnosticSignInfo = { fg = colors.blue },
			DiagnosticSignHint = { fg = colors.cyan },

			-- Git Signs
			GitSignsAdd = { fg = colors.green },
			GitSignsChange = { fg = colors.blue },
			GitSignsDelete = { fg = colors.red },

			-- Telescope (Koda-inspired)
			TelescopeBorder = { fg = colors.paren, bg = colors.bg },
			TelescopePromptBorder = { fg = colors.emphasis, bg = colors.bg },
			TelescopeResultsBorder = { fg = colors.paren, bg = colors.bg },
			TelescopePreviewBorder = { fg = colors.paren, bg = colors.bg },
			TelescopePromptNormal = { fg = colors.fg, bg = colors.bg },
			TelescopeResultsNormal = { fg = colors.fg, bg = colors.bg },
			TelescopePreviewNormal = { fg = colors.fg, bg = colors.bg },
			TelescopePromptPrefix = { fg = colors.emphasis },
			TelescopePromptTitle = { fg = colors.bg, bg = colors.emphasis, bold = true },
			TelescopeResultsTitle = { fg = colors.bg, bg = colors.green, bold = true },
			TelescopePreviewTitle = { fg = colors.bg, bg = colors.blue, bold = true },
			TelescopeSelection = { bg = colors.selection },
			TelescopeMatching = { fg = colors.orange, bold = true },

			-- Trouble
			TroubleNormal = { fg = colors.fg, bg = colors.bg },
			TroubleText = { fg = colors.fg },

			-- Which Key (Koda-inspired)
			WhichKey = { fg = colors.emphasis },
			WhichKeyGroup = { fg = colors.keyword },
			WhichKeyDesc = { fg = colors.fg },
			WhichKeySeparator = { fg = colors.comment },
			WhichKeyFloat = { bg = colors.bg_alt },

			-- Blink CMP (Koda-inspired)
			BlinkCmpMenu = { fg = colors.fg, bg = colors.bg_alt },
			BlinkCmpMenuBorder = { fg = colors.paren, bg = colors.bg_alt },
			BlinkCmpMenuSelection = { bg = colors.selection },
			BlinkCmpLabel = { fg = colors.fg },
			BlinkCmpLabelMatch = { fg = colors.emphasis, bold = true },
			BlinkCmpKind = { fg = colors.keyword },

			-- Lualine (Koda-inspired)
			LualineNormal = { fg = colors.bg, bg = colors.emphasis },
			LualineInsert = { fg = colors.bg, bg = colors.green },
			LualineVisual = { fg = colors.bg, bg = colors.blue },
			LualineReplace = { fg = colors.bg, bg = colors.red },
			LualineCommand = { fg = colors.bg, bg = colors.orange },

			-- Neogit
			NeogitDiffAdd = { fg = colors.green, bg = colors.bg_alt },
			NeogitDiffDelete = { fg = colors.red, bg = colors.bg_alt },
			NeogitHunkHeader = { fg = colors.fg, bg = colors.bg_highlight },
			NeogitHunkHeaderHighlight = { fg = colors.blue, bg = colors.bg_highlight },

			-- Harpoon
			HarpoonBorder = { fg = colors.fg_dim, bg = colors.bg_alt },
			HarpoonWindow = { fg = colors.fg, bg = colors.bg_alt },

			-- Fidget
			FidgetTitle = { fg = colors.blue },
			FidgetTask = { fg = colors.fg_dim },

			-- Mini (Koda-inspired)
			MiniStarterHeader = { fg = colors.emphasis },
			MiniStarterFooter = { fg = colors.comment },
			MiniStarterItem = { fg = colors.fg },
			MiniStarterItemBullet = { fg = colors.emphasis },
			MiniStarterItemPrefix = { fg = colors.orange },
			MiniStarterSection = { fg = colors.keyword },
			MiniStarterQuery = { fg = colors.green },
		}

		vim.cmd("hi clear")
		vim.o.termguicolors = true
		vim.g.colors_name = "cursor-midnight"

		for group, opts in pairs(highlights) do
			vim.api.nvim_set_hl(0, group, opts)
		end
	end,
}
