return {
	dir = vim.fn.stdpath("config"),
	name = "oc-1",
	lazy = false,
	priority = 1000,
	config = function()
		local palettes = {
			light = {
				bg = "#f8f7f7",
				bg_alt = "#f1f0f0",
				bg_highlight = "#fdfcfc",
				bg_stronger = "#fcfcfc",
				fg = "#656363",
				fg_weak = "#8e8b8b",
				fg_weaker = "#bcbbbb",
				fg_strong = "#211e1e",
				border = "#cfcecd",
				border_weak = "#dad9d9",
				selection = "#daeaff",
				cursor_line = "#f1f0f0",
				line_nr = "#bcbbbb",
				blue = "#034cff",
				cyan = "#0092a8",
				green = "#008600",
				yellow = "#917500",
				orange = "#d68c27",
				red = "#da3319",
				magenta = "#ed6dc8",
				string = "#006656",
				primitive = "#fb4804",
				type = "#d68c27",
				constant = "#007b80",
				property = "#ed6dc8",
				diff_add_bg = "#dafbe0",
				diff_add_fg = "#318430",
				diff_delete_bg = "#ffe9e4",
				diff_delete_fg = "#da3319",
				search_bg = "#ffdc17",
				search_fg = "#211e1e",
				markdown_heading = "#d68c27",
				markdown_link = "#3b7dd8",
				markdown_code = "#3d9a57",
			},
			dark = {
				bg = "#131010",
				bg_alt = "#1c1717",
				bg_highlight = "#151313",
				bg_stronger = "#191515",
				fg = "#b7b1b1",
				fg_weak = "#7f7979",
				fg_weaker = "#645f5f",
				fg_strong = "#f1ecec",
				border = "#4b4646",
				border_weak = "#3e3939",
				selection = "#0c2a74",
				cursor_line = "#151313",
				line_nr = "#4b4646",
				blue = "#89b5ff",
				cyan = "#93e9f6",
				green = "#37db2e",
				yellow = "#f1a10d",
				orange = "#fab283",
				red = "#ff917b",
				magenta = "#ff9ae2",
				string = "#00ceb9",
				primitive = "#ffba92",
				type = "#fab283",
				constant = "#93e9f6",
				property = "#ff9ae2",
				diff_add_bg = "#1a2a19",
				diff_add_fg = "#9dde99",
				diff_delete_bg = "#3c140d",
				diff_delete_fg = "#ff917b",
				search_bg = "#fcd53a",
				search_fg = "#131010",
				markdown_heading = "#9d7cd8",
				markdown_link = "#fab283",
				markdown_code = "#7fd88f",
			},
		}

		local function palette()
			if vim.o.background == "light" then
				return palettes.light
			end
			return palettes.dark
		end

		local function apply()
			local c = palette()

			vim.cmd("hi clear")
			if vim.fn.exists("syntax_on") == 1 then
				vim.cmd("syntax reset")
			end

			vim.o.termguicolors = true
			vim.g.colors_name = "oc-1"

			local highlights = {
				Normal = { fg = c.fg, bg = c.bg },
				NormalNC = { fg = c.fg, bg = c.bg },
				NormalFloat = { fg = c.fg, bg = c.bg_highlight },
				FloatBorder = { fg = c.border, bg = c.bg_highlight },
				FloatTitle = { fg = c.markdown_heading, bg = c.bg_highlight, bold = true },
				SignColumn = { fg = c.fg_weak, bg = c.bg },
				LineNr = { fg = c.line_nr },
				CursorLineNr = { fg = c.fg_strong, bold = true },
				CursorLine = { bg = c.cursor_line },
				CursorColumn = { bg = c.cursor_line },
				ColorColumn = { bg = c.bg_alt },
				Conceal = { fg = c.fg_weak },
				Cursor = { fg = c.bg, bg = c.fg_strong },
				lCursor = { fg = c.bg, bg = c.fg_strong },
				Directory = { fg = c.markdown_link, bold = true },
				DiffAdd = { fg = c.diff_add_fg, bg = c.diff_add_bg },
				DiffDelete = { fg = c.diff_delete_fg, bg = c.diff_delete_bg },
				DiffChange = { fg = c.blue, bg = c.selection },
				DiffText = { fg = c.fg_strong, bg = c.blue },
				EndOfBuffer = { fg = c.bg },
				ErrorMsg = { fg = c.red, bold = true },
				VertSplit = { fg = c.border },
				WinSeparator = { fg = c.border },
				Folded = { fg = c.fg_weak, bg = c.bg_alt },
				FoldColumn = { fg = c.fg_weaker, bg = c.bg },
				Search = { fg = c.search_fg, bg = c.search_bg },
				IncSearch = { fg = c.search_fg, bg = c.blue },
				CurSearch = { fg = c.search_fg, bg = c.blue, bold = true },
				MatchParen = { fg = c.orange, bold = true },
				ModeMsg = { fg = c.fg_strong },
				MoreMsg = { fg = c.green },
				NonText = { fg = c.fg_weaker },
				Pmenu = { fg = c.fg, bg = c.bg_stronger },
				PmenuSel = { fg = c.fg_strong, bg = c.selection },
				PmenuSbar = { bg = c.bg_alt },
				PmenuThumb = { bg = c.border },
				Question = { fg = c.green },
				QuickFixLine = { fg = c.fg_strong, bg = c.selection },
				StatusLine = { fg = c.fg, bg = c.bg_alt },
				StatusLineNC = { fg = c.fg_weak, bg = c.bg_alt },
				TabLine = { fg = c.fg_weak, bg = c.bg_alt },
				TabLineFill = { bg = c.bg_alt },
				TabLineSel = { fg = c.fg_strong, bg = c.bg_highlight },
				Title = { fg = c.markdown_heading, bold = true },
				Visual = { bg = c.selection },
				VisualNOS = { bg = c.selection },
				WarningMsg = { fg = c.yellow, bold = true },
				Whitespace = { fg = c.fg_weaker },
				SpecialKey = { fg = c.fg_weaker },
				WildMenu = { fg = c.fg_strong, bg = c.selection },

				Comment = { fg = c.fg_weak, italic = true },
				Constant = { fg = c.constant },
				String = { fg = c.string },
				Character = { fg = c.string },
				Number = { fg = c.primitive },
				Boolean = { fg = c.primitive },
				Float = { fg = c.primitive },
				Identifier = { fg = c.fg_strong },
				Function = { fg = c.fg_strong },
				Statement = { fg = c.fg_weak },
				Conditional = { fg = c.fg_weak },
				Repeat = { fg = c.fg_weak },
				Label = { fg = c.fg_weak },
				Operator = { fg = c.fg },
				Keyword = { fg = c.fg_weak },
				Exception = { fg = c.fg_weak },
				PreProc = { fg = c.fg },
				Include = { fg = c.fg_weak },
				Define = { fg = c.fg_weak },
				Macro = { fg = c.primitive },
				PreCondit = { fg = c.fg_weak },
				Type = { fg = c.type },
				StorageClass = { fg = c.fg_weak },
				Structure = { fg = c.fg_weak },
				Typedef = { fg = c.fg_weak },
				Special = { fg = c.fg },
				SpecialChar = { fg = c.cyan },
				Tag = { fg = c.fg_strong },
				Delimiter = { fg = c.fg },
				SpecialComment = { fg = c.fg_weak },
				Debug = { fg = c.primitive },
				Underlined = { underline = true },
				Error = { fg = c.red },
				Todo = { fg = c.search_fg, bg = c.search_bg, bold = true },

				DiagnosticError = { fg = c.red },
				DiagnosticWarn = { fg = c.yellow },
				DiagnosticInfo = { fg = c.cyan },
				DiagnosticHint = { fg = c.blue },
				DiagnosticOk = { fg = c.green },
				DiagnosticSignError = { fg = c.red },
				DiagnosticSignWarn = { fg = c.yellow },
				DiagnosticSignInfo = { fg = c.cyan },
				DiagnosticSignHint = { fg = c.blue },
				DiagnosticSignOk = { fg = c.green },
				DiagnosticVirtualTextError = { fg = c.red, bg = c.bg_alt },
				DiagnosticVirtualTextWarn = { fg = c.yellow, bg = c.bg_alt },
				DiagnosticVirtualTextInfo = { fg = c.cyan, bg = c.bg_alt },
				DiagnosticVirtualTextHint = { fg = c.blue, bg = c.bg_alt },
				DiagnosticVirtualTextOk = { fg = c.green, bg = c.bg_alt },
				DiagnosticUnderlineError = { undercurl = true, sp = c.red },
				DiagnosticUnderlineWarn = { undercurl = true, sp = c.yellow },
				DiagnosticUnderlineInfo = { undercurl = true, sp = c.cyan },
				DiagnosticUnderlineHint = { undercurl = true, sp = c.blue },
				DiagnosticUnderlineOk = { undercurl = true, sp = c.green },
				DiagnosticFloatingError = { fg = c.red },
				DiagnosticFloatingWarn = { fg = c.yellow },
				DiagnosticFloatingInfo = { fg = c.cyan },
				DiagnosticFloatingHint = { fg = c.blue },

				GitSignsAdd = { fg = c.diff_add_fg },
				GitSignsChange = { fg = c.blue },
				GitSignsDelete = { fg = c.diff_delete_fg },
				GitSignsTopdelete = { fg = c.diff_delete_fg },
				GitSignsChangedelete = { fg = c.orange },
				GitSignsUntracked = { fg = c.fg_weak },
				Added = { fg = c.diff_add_fg },
				Changed = { fg = c.blue },
				Removed = { fg = c.diff_delete_fg },

				TelescopeNormal = { fg = c.fg, bg = c.bg },
				TelescopeBorder = { fg = c.border, bg = c.bg },
				TelescopePromptNormal = { fg = c.fg, bg = c.bg_highlight },
				TelescopePromptBorder = { fg = c.border, bg = c.bg_highlight },
				TelescopePromptPrefix = { fg = c.blue },
				TelescopePromptTitle = { fg = c.bg, bg = c.blue, bold = true },
				TelescopeResultsNormal = { fg = c.fg, bg = c.bg },
				TelescopeResultsBorder = { fg = c.border, bg = c.bg },
				TelescopeResultsTitle = { fg = c.bg, bg = c.orange, bold = true },
				TelescopePreviewNormal = { fg = c.fg, bg = c.bg },
				TelescopePreviewBorder = { fg = c.border, bg = c.bg },
				TelescopePreviewTitle = { fg = c.bg, bg = c.orange, bold = true },
				TelescopeSelection = { bg = c.selection, bold = true },
				TelescopeMatching = { fg = c.primitive, bold = true },

				WhichKey = { fg = c.fg_strong },
				WhichKeyGroup = { fg = c.fg_weak },
				WhichKeyDesc = { fg = c.fg },
				WhichKeySeparator = { fg = c.fg_weaker },
				WhichKeyValue = { fg = c.fg_weak },
				WhichKeyFloat = { bg = c.bg_highlight },
				WhichKeyBorder = { fg = c.border, bg = c.bg_highlight },

				TroubleNormal = { fg = c.fg, bg = c.bg },
				TroubleNormalNC = { fg = c.fg, bg = c.bg },
				TroubleText = { fg = c.fg },
				TroubleCount = { fg = c.bg, bg = c.blue, bold = true },

				BlinkCmpMenu = { fg = c.fg, bg = c.bg_highlight },
				BlinkCmpMenuBorder = { fg = c.border, bg = c.bg_highlight },
				BlinkCmpMenuSelection = { bg = c.selection },
				BlinkCmpLabel = { fg = c.fg },
				BlinkCmpLabelMatch = { fg = c.blue, bold = true },
				BlinkCmpKind = { fg = c.fg_weak },

				MiniStarterHeader = { fg = c.markdown_heading, bold = true },
				MiniStarterFooter = { fg = c.fg_weak },
				MiniStarterItem = { fg = c.fg },
				MiniStarterItemBullet = { fg = c.blue },
				MiniStarterItemPrefix = { fg = c.orange },
				MiniStarterSection = { fg = c.fg_weak },
				MiniStarterQuery = { fg = c.green },

				NeogitDiffAdd = { fg = c.diff_add_fg, bg = c.diff_add_bg },
				NeogitDiffDelete = { fg = c.diff_delete_fg, bg = c.diff_delete_bg },
				NeogitHunkHeader = { fg = c.fg, bg = c.bg_alt },
				NeogitHunkHeaderHighlight = { fg = c.blue, bg = c.bg_alt },
				NeogitBranch = { fg = c.orange, bold = true },
				NeogitRemote = { fg = c.green, bold = true },

				HarpoonBorder = { fg = c.border, bg = c.bg_highlight },
				HarpoonWindow = { fg = c.fg, bg = c.bg_highlight },

				FidgetTitle = { fg = c.blue },
				FidgetTask = { fg = c.fg_weak },

				markdownHeadingDelimiter = { fg = c.markdown_heading },
				markdownH1 = { fg = c.markdown_heading, bold = true },
				markdownH2 = { fg = c.markdown_heading, bold = true },
				markdownH3 = { fg = c.markdown_heading, bold = true },
				markdownH4 = { fg = c.markdown_heading, bold = true },
				markdownH5 = { fg = c.markdown_heading, bold = true },
				markdownH6 = { fg = c.markdown_heading, bold = true },
				markdownLinkText = { fg = c.markdown_link, underline = true },
				markdownUrl = { fg = c.markdown_link, underline = true },
				markdownCode = { fg = c.markdown_code },
				markdownCodeBlock = { fg = c.fg_strong },
				markdownBold = { fg = c.markdown_heading, bold = true },
				markdownItalic = { fg = c.orange, italic = true },

				["@comment"] = { link = "Comment" },
				["@comment.todo"] = { fg = c.search_fg, bg = c.search_bg, bold = true },
				["@comment.note"] = { fg = c.bg, bg = c.blue, bold = true },
				["@comment.warning"] = { fg = c.search_fg, bg = c.search_bg, bold = true },
				["@comment.error"] = { fg = c.bg, bg = c.red, bold = true },
				["@variable"] = { fg = c.fg_strong },
				["@variable.builtin"] = { fg = c.fg },
				["@variable.parameter"] = { fg = c.fg, italic = true },
				["@variable.member"] = { fg = c.property },
				["@constant"] = { fg = c.constant },
				["@constant.builtin"] = { fg = c.constant },
				["@constant.macro"] = { fg = c.primitive },
				["@module"] = { fg = c.fg },
				["@label"] = { fg = c.fg_weak },
				["@string"] = { fg = c.string },
				["@string.escape"] = { fg = c.cyan },
				["@string.regexp"] = { fg = c.cyan },
				["@character"] = { fg = c.string },
				["@number"] = { fg = c.primitive },
				["@number.float"] = { fg = c.primitive },
				["@boolean"] = { fg = c.primitive },
				["@type"] = { fg = c.type },
				["@type.builtin"] = { fg = c.type },
				["@type.definition"] = { fg = c.type },
				["@attribute"] = { fg = c.fg_weak },
				["@property"] = { fg = c.property },
				["@function"] = { fg = c.fg_strong },
				["@function.call"] = { fg = c.fg_strong },
				["@function.builtin"] = { fg = c.fg_strong },
				["@function.macro"] = { fg = c.fg_strong },
				["@function.method"] = { fg = c.fg_strong },
				["@function.method.call"] = { fg = c.fg_strong },
				["@constructor"] = { fg = c.fg_strong },
				["@operator"] = { fg = c.fg },
				["@keyword"] = { fg = c.fg_weak },
				["@keyword.coroutine"] = { fg = c.fg_weak },
				["@keyword.function"] = { fg = c.fg_weak },
				["@keyword.operator"] = { fg = c.fg_weak },
				["@keyword.import"] = { fg = c.fg_weak },
				["@keyword.storage"] = { fg = c.fg_weak },
				["@keyword.repeat"] = { fg = c.fg_weak },
				["@keyword.return"] = { fg = c.fg_weak },
				["@keyword.exception"] = { fg = c.fg_weak },
				["@keyword.conditional"] = { fg = c.fg_weak },
				["@punctuation.delimiter"] = { fg = c.fg },
				["@punctuation.bracket"] = { fg = c.fg },
				["@punctuation.special"] = { fg = c.fg },
				["@markup.heading"] = { fg = c.markdown_heading, bold = true },
				["@markup.strong"] = { bold = true },
				["@markup.italic"] = { italic = true },
				["@markup.link"] = { fg = c.markdown_link, underline = true },
				["@markup.link.url"] = { fg = c.markdown_link, underline = true },
				["@markup.raw"] = { fg = c.markdown_code },
				["@markup.list"] = { fg = c.markdown_link },
				["@tag"] = { fg = c.fg_strong },
				["@tag.attribute"] = { fg = c.property },
				["@tag.delimiter"] = { fg = c.fg },

				["@lsp.type.class"] = { fg = c.type },
				["@lsp.type.decorator"] = { fg = c.fg_weak },
				["@lsp.type.enum"] = { fg = c.type },
				["@lsp.type.enumMember"] = { fg = c.constant },
				["@lsp.type.function"] = { fg = c.fg_strong },
				["@lsp.type.interface"] = { fg = c.type },
				["@lsp.type.macro"] = { fg = c.primitive },
				["@lsp.type.method"] = { fg = c.fg_strong },
				["@lsp.type.namespace"] = { fg = c.fg },
				["@lsp.type.parameter"] = { fg = c.fg, italic = true },
				["@lsp.type.property"] = { fg = c.property },
				["@lsp.type.struct"] = { fg = c.type },
				["@lsp.type.type"] = { fg = c.type },
				["@lsp.type.typeParameter"] = { fg = c.type },
				["@lsp.type.variable"] = { fg = c.fg_strong },
			}

			for group, opts in pairs(highlights) do
				vim.api.nvim_set_hl(0, group, opts)
			end

			vim.g.terminal_color_0 = c.bg_alt
			vim.g.terminal_color_1 = c.red
			vim.g.terminal_color_2 = c.green
			vim.g.terminal_color_3 = c.yellow
			vim.g.terminal_color_4 = c.blue
			vim.g.terminal_color_5 = c.magenta
			vim.g.terminal_color_6 = c.cyan
			vim.g.terminal_color_7 = c.fg
			vim.g.terminal_color_8 = c.fg_weaker
			vim.g.terminal_color_9 = c.red
			vim.g.terminal_color_10 = c.green
			vim.g.terminal_color_11 = c.search_bg
			vim.g.terminal_color_12 = c.blue
			vim.g.terminal_color_13 = c.magenta
			vim.g.terminal_color_14 = c.cyan
			vim.g.terminal_color_15 = c.fg_strong
		end

		apply()

		local group = vim.api.nvim_create_augroup("oc1_theme", { clear = true })
		vim.api.nvim_create_autocmd("OptionSet", {
			group = group,
			pattern = "background",
			callback = function()
				vim.schedule(apply)
			end,
			desc = "Reapply OC-1 highlights when background changes",
		})
	end,
}
